### ISSUE TITLE
[enhancement] Should Genie add support to NetworkAttachmentDefinition CRDs?

### ISSUE THREAD

**Issue by yuvalif** [cni-genie/CNI-Genie#135]
see: https://github.com/intel/multus-cni/blob/master/examples/crd.yml

Could be done **in addition** to the existing mechanism (using different pod annotation), but probably not both on the same pod.

The existing mechanism is more simplified, however, using CRD will allow more fine grained requests from the underlying CNIs.

**Comment by sushanthakumar** [comment]
@yuvalif , definitely we will analyse your proposal and get back to u, thanks

**Comment by m1093782566** [comment]
@yuvalif We are currently analyzing the amount of work of implementing the Kubernetes Network Plumbing Working Group multi-network CRD de-facto specification V1, xerf: https://github.com/kubernetes/community/pull/2665.

Would be happy to see more people can get involved in.

**Comment by yuvalif** [comment]
@m1093782566 as part of the [Kubevirt](https://github.com/kubevirt/kubevirt) project we recently added support for the Genie CNI: https://github.com/kubevirt/kubevirt/pull/1590 (this is in addition to the support we already have for the Multus CNI).

**Comment by sushanthakumar** [comment]
@yuvalif , Great to know the genie incorporation in your project. We also would love to have network crd specification incorporated in genie and working on it, will keep you updated

**Comment by sushanthakumar** [comment]
@yuvalif , This feature is implemented and merged to our master a week ago. You can have a try, thanks for request for this requirement

**Comment by yuvalif** [comment]
@sushanthakumar, this is great, will have a look (I see documentation is here: https://github.com/Huawei-PaaS/CNI-Genie/blob/master/docs/network-attachment-definitions/README.md)
