### ISSUE TITLE
Mac address info missing in network status annotation

### ISSUE THREAD

**Issue by sushanthakumar** [cni-genie/CNI-Genie#174]
**What happened**:
Mac address info missing in network status annotation when we use networkattachment definition to get ip address.

![image](https://user-images.githubusercontent.com/30930862/55711931-6066ca00-5a0b-11e9-92c7-850a763d4807.png)

**What you expected to happen**:
Mac address associated should be displayed as part of status annotation

**How to reproduce it (as minimally and precisely as possible)**:
create networkattachmentdefinition and attach it to pod
Observe network status annotation field

**Anything else we need to know?**: -NA-

**Comment by sandhyaravi** [comment]
It depends on plugin we use. If plugin provides mac address, then genie displays it. In below example macvlan is used and we can see mac address output in status section. It is not an issue.
![image](https://user-images.githubusercontent.com/13521135/56013836-51845e00-5d10-11e9-9665-ff9126f5a07e.png)
