### ISSUE TITLE
DCO is missing for the CNI-Genie project

### ISSUE THREAD

**Issue by idvoretskyi** [cni-genie/CNI-Genie#217]
Greetings, project maintainers.

CNCF's IP policy (https://github.com/cncf/foundation/blob/master/charter.md#11-ip-policy) requires all projects to use either CLA (Contributor License Agreements) or DCO (Developer Certificate of Origin). Unless there's a strong necessity to use CLA, we encourage projects to use DCO as it's easier to setup and use. Ref.: https://github.com/cncf/foundation/issues/130

During the audit, we've noticed that your project doesn't have DCO enabled. Please enable DCO for all repositories in your GitHub organization. You may find more details here - https://github.com/apps/dco.

Thanks

**Comment by kevin-wangzefeng** [comment]
Thanks Ihor, DCO has been enabled, see https://github.com/cni-genie/CNI-Genie/pull/218 for example :-)

**Comment by idvoretskyi** [comment]
Awesome, thanks @kevin-wangzefeng!
